FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker


# =========================
# FINAL RUNTIME IMAGE
# =========================
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache poppler-utils ca-certificates

COPY --from=builder /app/worker .
COPY --from=builder /app/pkg/cert/ca.pem /app/pkg/cert/ca.pem

CMD ["./worker"]